services:
  - type: web
    name: mgnrega-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: USE_DATABASE
        value: true
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: mgnrega-db
    plan: free
    databaseName: mgnrega
    user: mgnrega_user

